//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuAn1_QLThuVien
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLThuVienEntities1 : DbContext
    {
        public QLThuVienEntities1()
            : base("name=QLThuVienEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NguoiDoc> NguoiDocs { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<PhieuMuon> PhieuMuons { get; set; }
        public virtual DbSet<PhieuTra> PhieuTras { get; set; }
        public virtual DbSet<Sach> Saches { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
        public virtual DbSet<TheHoiVien> TheHoiViens { get; set; }
    
        public virtual int doimatkhau(string tendangnhap, string matkhau, string matkhaumoi)
        {
            var tendangnhapParameter = tendangnhap != null ?
                new ObjectParameter("tendangnhap", tendangnhap) :
                new ObjectParameter("tendangnhap", typeof(string));
    
            var matkhauParameter = matkhau != null ?
                new ObjectParameter("matkhau", matkhau) :
                new ObjectParameter("matkhau", typeof(string));
    
            var matkhaumoiParameter = matkhaumoi != null ?
                new ObjectParameter("matkhaumoi", matkhaumoi) :
                new ObjectParameter("matkhaumoi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("doimatkhau", tendangnhapParameter, matkhauParameter, matkhaumoiParameter);
        }
    
        public virtual ObjectResult<string> sp_DanhSach_MaThe()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_DanhSach_MaThe");
        }
    }
}
