//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuAn1_QLThuVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuTra
    {
        public int MaPhieuTra { get; set; }
        public int MaPhieuMuon { get; set; }
        public string MaND { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<System.DateTime> NgayHenTra { get; set; }
        public Nullable<System.DateTime> NgayTra { get; set; }
        public Nullable<double> PhiTra { get; set; }
        public string TinhTrang { get; set; }
        public Nullable<int> SoGio { get; set; }
    
        public virtual PhieuMuon PhieuMuon { get; set; }
    }
}
