//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuAn1_QLThuVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class TheHoiVien
    {
        public string MaThe { get; set; }
        public string MaND { get; set; }
        public string TenHoiVien { get; set; }
        public string DiaChi { get; set; }
        public System.DateTime NgayDangKi { get; set; }
        public System.DateTime NgayHetHan { get; set; }
        public Nullable<int> DiemHoiVien { get; set; }
    
        public virtual NguoiDoc NguoiDoc { get; set; }
    }
}
